name:                dt-haskell
version:             0.1.0.0
github:              "githubuser/dt-haskell"
license:             BSD3
author:              "Pacal Poizat"
maintainer:          "pascal.poizat@gmail.com"
copyright:           "2018 Pascal Poizat"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dt-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- singletons >= 2.4 && < 2.5
- type-natural >= 0.8 

library:
  source-dirs: src

executables:
  dt-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwarn-unused-imports
    - -fwarn-incomplete-uni-patterns
    - -fwarn-incomplete-patterns
    - -fwarn-overlapping-patterns
    - -fwarn-missing-signatures
    - -fwarn-name-shadowing
    dependencies:
    - dt-haskell

tests:
  dt-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwarn-unused-imports
    - -fwarn-incomplete-uni-patterns
    - -fwarn-incomplete-patterns
    - -fwarn-overlapping-patterns
    - -fwarn-missing-signatures
    - -fwarn-name-shadowing
    dependencies:
    - dt-haskell
